server:
  port: 9010
  servlet:
    context-path: /consumer
spring:
  application:
    name: Consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  datasource:
    url: jdbc:mysql://192.168.31.100:3306/scheduled_demo?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-location: classpath:mapper/*.xml

  management:
  endpoints:
    web:
      exposure:
        include: '*'
